object TelaF: TTelaF
  Left = 0
  Top = 0
  ClientHeight = 451
  ClientWidth = 767
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  Padding.Left = 1
  Padding.Top = 1
  Padding.Right = 1
  Padding.Bottom = 1
  OldCreateOrder = True
  Visible = True
  WindowState = wsMaximized
  PixelsPerInch = 96
  TextHeight = 13
end
